# Render Blueprint - Django + Poetry + WhiteNoise

services:
  - type: web
    name: django-app
    env: python
    plan: free
    autoDeploy: true

    buildCommand: |
      poetry install --no-root --only main
      python manage.py collectstatic --noinput

    startCommand: |
      python manage.py migrate && gunicorn config.wsgi:application --workers=2 --threads=4 --timeout=60 --preload

    healthCheckPath: /
    healthCheckTimeout: 100

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      # Cambia esto después del primer deploy con tu URL real
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://your-service-name.onrender.com"
      - key: TIME_ZONE
        value: "America/Mexico_City"

      # —— Postgres ——
      - key: DB_ENGINE
        value: "postgres"
      - key: DB_SSL_REQUIRE
        value: "true"
      - key: POSTGRES_DB
        fromDatabase:
          name: django-postgres
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: django-postgres
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: django-postgres
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: django-postgres
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: django-postgres
          property: port

# Base de datos Postgres gestionada por Render (nivel raíz, alineado con 'services')
databases:
  - name: django-postgres
    plan: free
