# Generated by Django 4.2.4 on 2025-10-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Número visible de habitación (ej. 101)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("floor", models.IntegerField(blank=True, null=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("double", "Double"),
                            ("suite", "Suite"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=1)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio base por noche",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="available",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="hotel_room_status_b531da_idx"
                    ),
                    models.Index(
                        fields=["room_type"], name="hotel_room_room_ty_a964c2_idx"
                    ),
                ],
            },
        ),
    ]
