# Generated by Django 4.2.4 on 2025-10-09 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_name", models.CharField(max_length=120)),
                ("guests_count", models.PositiveIntegerField(default=1)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("checked_in", "Checked in"),
                            ("checked_out", "Checked out"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="reserved",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="hotel.room",
                    ),
                ),
            ],
            options={
                "ordering": ["-check_in", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["room", "check_in", "check_out"],
                        name="hotel_booki_room_id_63801d_idx",
                    ),
                    models.Index(
                        fields=["status"], name="hotel_booki_status_0f45ee_idx"
                    ),
                ],
            },
        ),
    ]
